Apostas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views 
from .views import ( 
                    Apostar, 
                    ApostasListView, 
                    JogadoresListView, 
                    PartidasListView,
                    PartidaDetailView, 
                    PartidaUpdateView,
                    EntregarPremio,
                    PartidaConcluida 
                    ) 


app_name = 'blog'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('sair/', auth_views.LogoutView.as_view(),name='sair'),
    path('partidas/', PartidasListView.as_view(), name='partidas'),
    path('partida/<int:pk>/', PartidaDetailView.as_view(), name='partida'),
    path('partida/<int:pk>/vencedores', PartidaConcluida, name='vencedores'),
    path('partida/<int:pk>/premiar', EntregarPremio, name='premiar-vencedores'),
    path('apostas/', ApostasListView.as_view(), name='apostas'),
    path('jogadores/', JogadoresListView.as_view(), name='jogadores'),
    path('apostar/<int:idpartida>/', Apostar, name='apostar'),
    path('partida/<int:pk>/update', PartidaUpdateView.as_view(), name='partida-update'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Credito(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    valor = models.DecimalField(default=100,max_digits=11,decimal_places=2)
    
    def __str__(self):
        return f'{self.user.username} - valor: {self.valor} AO'
    
    
class Equipe(models.Model):
    nome = models.CharField(max_length=50,unique=True,null=False,blank=False)
    
    def __str__(self):
        return f'{self.nome}'
    
    
class Partida(models.Model):
    equipe1 = models.ForeignKey(Equipe,related_name='equipe1',on_delete=models.CASCADE,verbose_name='1ª Equipe')
    equipe2 = models.ForeignKey(Equipe,related_name='equipe2',on_delete=models.CASCADE,verbose_name='2ª Equipe')
    placar1 = models.IntegerField(verbose_name='Placar 1',default=0,help_text='Indica o total de golos da 1ª equipe')
    placar2 = models.IntegerField(verbose_name='Placar 2',default=0,help_text='Indica o total de golos da 2ª equipe')
    data_criada = models.DateTimeField(auto_now_add=True,verbose_name='Data de criação')
    data_partida = models.DateTimeField(default=None,verbose_name='Data da partida')
    concluido = models.BooleanField(default=False)
    encerrado = models.BooleanField(default=False,help_text='Indica se os jogadores ja receberam os prêmios')
    
    
    def __str__(self):
        return f'{self.equipe1.nome} vs {self.equipe2.nome}'
    
    def get_absolute_url(self):
        return reverse('blog:vencedores', kwargs={'pk': self.pk})
    
        
class Aposta(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='apostas')
    partida = models.ForeignKey(Partida,on_delete=models.CASCADE,related_name='apostas')
    placar1 = models.IntegerField(verbose_name='Placar 1',default=0,help_text='Indica o total de golos da 1ª equipe')
    placar2 = models.IntegerField(verbose_name='Placar 2',default=0,help_text='Indica o total de golos da 2ª equipe')
    valor = models.DecimalField(default=5,max_digits=11,decimal_places=2)
    
    def __str__(self):
        return f'{self.user.username} - {self.partida.equipe1} vs {self.partida.equipe2} '
    
    class Meta:
        unique_together = (('user','partida'))


class Ranking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='vitorias')
    aposta = models.ForeignKey(Aposta,on_delete=models.CASCADE,related_name='ranking')
    premio = models.DecimalField(default=5,max_digits=11,decimal_places=2)
    data_criada = models.DateTimeField(auto_now_add=True,verbose_name='Data de criação')

    def __str__(self):
        return f'{self.user.username}, Victória: {self.aposta.partida.equipe1} vs {self.aposta.partida.equipe2}'

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Credito, Aposta

        
# class UserUpdateForm(forms.ModelForm):
    
#     class Meta:
#         model = User
#         fields = ['username','first_name','last_name'] 
        

# class FormApostar(forms.ModelForm):    
#     class Meta:
#         model = Aposta
#         fields = [] 

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.db import IntegrityError
from django.contrib import messages

from .utils import contextVencedores
from .models import Partida, Aposta, User, Ranking


class PartidasListView(LoginRequiredMixin, ListView):
    model = Partida
    template_name = 'blog/partidas.html'
    context_object_name = 'partidas'
    ordering = ['-id']
    paginate_by = 5


class PartidaDetailView(LoginRequiredMixin, DetailView):
    model = Partida
    template_name = 'blog/apostar.html'
    context_object_name = 'partida'


@login_required
def PartidaConcluida(request, pk):
    return render(request, 'blog/partida-detail.html', contextVencedores(pk))
    
    
class PartidaUpdateView(LoginRequiredMixin, UpdateView):
    model = Partida
    template_name = 'blog/atualizarPartida.html'
    context_object_name = 'partida'
    fields = ['placar1','placar2','concluido']
    
    # Verificar se o usuário que está tentar editar o post é o mesmo que criou
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
    
class ApostasListView(LoginRequiredMixin, ListView):
    model = Aposta
    template_name = 'blog/apostas.html'
    context_object_name = 'apostas'
    ordering = ['-id']
    paginate_by = 5
    
    # Sobrescrever a queryset padrão da ListView
    def get_queryset(self):
        return Aposta.objects.filter(user=self.request.user).order_by('-id')


class JogadoresListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'blog/jogadores.html'
    context_object_name = 'jogadores'
    ordering = ['-credito__valor']
    paginate_by = 5


def Apostar(request, idpartida):
    """[Efectuar Apostas]
    Este metodo serve para criar uma nova aposta,
    primeiramente é selecionada a partida e o usuario que está efectuando a ação,
    depois é verificado se o jogador tem saldo suficiente na conta para efectuar a aposta.    
    """
    try:

        if request.method=='POST':
            
            partida = get_object_or_404(Partida, pk=idpartida)
            user = request.user
            valor_fixo = 50
            
            # Verificar se o jogador tem saldo suficiente para apostar
            if user.credito.valor >= valor_fixo:
                # Efectuar o desconto do credito do jogador para concluir a aposta
                user.credito.valor -= valor_fixo                
                # Criar a instancia da aposta para salvar os dados na BD.
                aposta = Aposta(user=user, partida=partida, placar1=request.POST['placar1'], placar2=request.POST['placar2']) 
                aposta.save() # salvar a aposta.
                user.save()
                
                # Criar mensagem de sucesso, pois a operação for efectuada com sucesso.
                messages.success(request,f'Aposta da partida {partida.equipe1} vs {partida.equipe2} efectuada com sucesso!')
            else:
                # Criar mensagem de erro, porque o usuario não tem valor suficiente para apostar.
                messages.error(request,'ups!!! O seu saldo é insuficiente para efectuar esta operação, recarregue o seu cartão para continuar apostar.')

                # Redirecionar o usuario para rota de partidas.
                return redirect('blog:partidas') 
            
    except IntegrityError: # O sistema cairá nesta excessão de erro caso tentar apostar mais de uma vez numa partida. 
        messages.error(request,'Não é possivel efectuar múltiplas apostas em uma partida, por favor selecione outra partida.')
        return redirect('blog:partidas')

    return redirect('blog:apostas')


def EntregarPremio(request, pk):
    
    mensagem = ''
    data = contextVencedores(pk)
    vencedores = data['vencedores']
    apostadores = data['apostadores']
    premio = data["aposta"]["premio"]

    if len(vencedores) > 0 :
        for aposta in data['vencedores']:
            user = aposta.user
            user.credito.valor += premio
            Ranking.objects.create(user=user, aposta=aposta, premio=premio)
            user.save()        
        # Criar mensagem de sucesso, pois a operação foi efectuada com sucesso.
        mensagem = f'Premio distribuido para {len(vencedores)} jogador(es) com sucesso...'

    elif apostadores:
        print(apostadores)
        for aposta in apostadores :
            user = aposta.user
            user.credito.valor += 5
            user.save()
        mensagem = f'Valor de aposta devolvido para {len(apostadores)} jogador(es) com sucesso...'
    
    #Encerrar a premiação das partidas
    partida = data['partida']
    partida.encerrado = True
    partida.save()
    
    messages.success(request,mensagem)
    
    return redirect('blog:jogadores')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/apostar.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="span6">
    <h2>Apostar na partida de {{partida.equipe1}} vs {{partida.equipe2}}</h2>
    <hr/>
        <form class="form-horizontal" action="{% url 'blog:apostar' partida.id %}" method="POST">
        {% csrf_token %}
        <fieldset>

            <div class="control-group">
            <div class="controls">
                <span style='margin-right: 3px;'>{{partida.equipe1}}</span> 
                <input class="input-small" name='placar1' type="number" value="0">
                <span style='color: #ccc;'> - </span> 
                <input class="input-small" name='placar2' type="number" value="0">
                <span style='margin-left: 3px;'>{{partida.equipe2}}</span> 
            </div>
            </div>

            <div class="form-actions">
            <button class="btn btn-primary" type="submit">Confirmar</button>
            <a class="btn" href="{% url 'blog:partidas' %}">Cancelar</a>
            </div>
        </fieldset>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/apostas.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="span9">
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header"><h3><i class="icon-play"></i> Minhas Apostas</h3></div>
        <div class="box-content">
            <div class="content-inner">
                <div class="marg20-btm">
                    Total de apostas <span class="badge badge-inverse">{{apostas|length}}</span>
                    <form class="form-inline pull-right">
                        <input type="text" placeholder="Pesquisar aposta">
                        <input class="btn" type="submit" value="Search">
                    </form>
                </div>
                
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>ID. Partida</th>
                            <th>Partida</th>
                            <th>Resultado Final</th>
                            <th>Meu Resultado</th>
                            <th>Data da partida</th>
                            <th>Estado da partida</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% comment %} Mostrando a apostas cadastrados {% endcomment %}
                {% if apostas %}
                    {% for aposta in apostas %}   
                        <tr>
                            <td><p>{{ aposta.pk }}</p></td>
                            <td><p>{{ aposta.partida.pk }}</p></td>
                            <td><p>{{ aposta.partida.equipe1 }} vs {{ aposta.partida.equipe2 }}</p></td>
                            <td><p>{{ aposta.partida.placar1 }} - {{ aposta.partida.placar2 }}</p></td>
                            <td><p>{{ aposta.placar1 }} - {{ aposta.placar2 }}</p></td>
                            <td><p>{{ aposta.partida.data_partida }}</p></td>
                            {% if  aposta.partida.concluido %}
                                <td><span class="label label-success">Concuída</span></td>
                            {% else %}
                                <td><span class="label label-important">Pendente</span></td>                        
                            {% endif %}
                        </tr>
                {% endfor %}
                {% endif %}
                    </tbody>
                </table>
                
    <!-- Paginação -->
    <div class="col-md-10 mb-4">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">Primeiro</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">←</a>
        {% endif %}        
 
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num <  page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">→</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
        {% endif %}        
        
    {% endif %}
    </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

blog/templates/blog/atualizarPartida.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="span6">
    <h3>Atualizar partida de {{partida.equipe1}} vs {{partida.equipe2}}</h3>
    <hr/>

    <div style="display: flex; justify-content: center;">
    <div class="border-caixa">
        <!-- formulario de Postagem -->
        <form method="POST">
            {% csrf_token %}
            <div class="control-group">

            <div class="controls" style='margin-bottom: 15px;'>
                <span style='margin-right: 3px;'>{{partida.equipe1}}</span> 
                <input class="input-small" name='placar1' type="number" value="{{partida.placar1}}"/>
                <span style='color: #ccc;'> - </span> 
                <input class="input-small" name='placar2' type="number" value="{{partida.placar2}}"/>
                <span style='margin-left: 3px;'>{{partida.equipe2}}</span> 
            </div>

            <div class="login-actions">
                <span class="login-checkbox">
                    <input name="concluido" id="Field" class="field login-checkbox" 
                    type="checkbox" {% if partida.concluido %}checked{% endif %} value="true"/>
                    <label class="choice" for="Field">Concluido</label>
				</span>
                
                <br/>
                <br/>
                <a class="btn-signin btn" href="{% url 'blog:partidas' %}">Cancelar</a>
				<input name="submit" class="btn-signin btn btn-primary" type="submit" value="Atualizar"/>
			</div>
        </form>
    </div>
    </div>     
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8" />
    <title>Apostas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!-- Le styles -->
    <link href="{% static 'blog/css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/mbooh.css' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/icon-style.css ' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/bootstrap-responsive.css ' %}" rel="stylesheet" />
    <link href="{% static 'blog/css/apostas.css' %}" rel="stylesheet" />

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Apostas</a>
          <div class="nav-collapse">
            <ul class="nav">
                <li><a data-toggle="modal" href="#notif"><i class="icon-white icon-inbox"></i> Crédito <span class="badge badge-info">{{user.credito.valor}} AO</span></a></li>
            </ul>
            <ul class="nav pull-right">

            <li class="dropdown">
              <a href="" class="dropdown-toggle" style='font-size:14px;' data-toggle="dropdown">{{user.username}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"><i class="icon-user"></i> Perfil</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:sair' %}"><i class="icon-off"></i> Sair</a></li>
              </ul>
            </li>

          </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="menu-head">
        <div class="container-fluid">
            <ul class="nav nav-tabs">
                <li class="active"><a href="partidas.html">Menu</a></li>
            </ul>
        </div>
    </div>
    
    {% comment %} Imprimir mensagens caso for enviada uma mensagem {% endcomment %}
    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
    {% endif %}

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <ul class="nav nav-tabs nav-stacked">
                    <li class="active"><a href="{% url 'blog:partidas' %}">Partidas</a></li>
                    <li><a href="{% url 'blog:apostas' %}">Apostas</a></li>
                    <li><a href="{% url 'blog:jogadores' %}"> Jogadores</a></li>

                    {% comment %} verificar se o usuario faz parte da equipe de administração do site {% endcomment %}
                     {% if user.is_staff %}
                        <li><a href="/admin">Admin</a></li>
                     {% endif %}

                </ul>
            </div>
            
      
      {% block content %}
      {% endblock content %}


        </div> 
    </div> 
    
    <script src="{% static 'blog/js/jquery-1.7.2.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="{% static 'blog/js/mbooh.js' %}"></script>
  </body>
</html>

blog/templates/blog/jogadores.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="span9">
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header"><h3><i class="icon-play"></i> Lista de Ranking</h3></div>
        <div class="box-content">
            <div class="content-inner">
                <div class="marg20-btm">
                    Total de Jogadores <span class="badge badge-inverse">{{jogadores|length}}</span>
                    <form class="form-inline pull-right">
                        <input type="text" placeholder="Pesquisar jogador">
                        <input class="btn" type="submit" value="Search">
                    </form>
                </div>
                
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Crédito</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% comment %} Mostrando a jogadores cadastrados {% endcomment %}
                {% if jogadores %}
                    {% for jogador in jogadores %}   
                        <tr>
                            <td><p>{{ jogador.pk }}</p></td>
                            <td><p>{{ jogador.username }}</p></td>
                            <td><p>{{ jogador.credito.valor }} AO</p></td>
                        </tr>
                {% endfor %}
                {% endif %}
                    </tbody>
                </table>
                
    <!-- Paginação -->
    <div class="col-md-10 mb-4">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">Primeiro</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">←</a>
        {% endif %}        
 
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num <  page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">→</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
        {% endif %}        
        
    {% endif %}
    </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

blog/templates/blog/partida-detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="span9">
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header"><h3><i class="icon-play"></i> Lista de Vencedores</h3></div>
        <div class="box-content">
            <div class="content-inner">
                <div class="marg20-btm">
                <div style="margin-bottom: 10px;">
                    {% if partida.concluido %}
                        <span class="label label-success">Partida Concuída</span>
                    {% else %}
                        <span class="label label-important">Partida Pendente</span>
                    {% endif %}
                    |
                    Total. Apostas <span class="badge badge-warning">{{ aposta.totApostas }}</span>
                    | Total. Montante <span class="badge badge-info">AO {{ aposta.totMontant}}</span>
                    | Prêmio <span class="badge badge-success">AO {{ aposta.premio}}</span>

                </div>

                    <form class="form-inline pull-right">
                        <input type="text" placeholder="Pesquisar vencedor">
                        <input class="btn" type="submit" value="Search">
                    </form>
                </div>

                <h2>{{partida.equipe1}} vs {{partida.equipe2}}</h2>
                <hr/>
                {% comment %} Resultado Final {% endcomment %}
                  <div class="controls">
                    <span style='margin-right: 3px;'>{{partida.equipe1}}</span> 
                    <input class="input-small" name='placar1' type="number" value="{{partida.placar1}}">
                    <span style='color: #ccc;'> - </span> 
                    <input class="input-small" name='placar2' type="number" value="{{partida.placar2}}">
                <span style='margin-left: 3px;'>{{partida.equipe2}}</span> 
                </div>

                <br/>
                
                {% if vencedores %}
                <h3>Lista de Vencedores</h3>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID. Aposta</th>
                            <th>Jogador</th>
                            <th>Valor Apostado</th>
                            <th>Prêmio</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% comment %} Mostrando a lista de todas partidas criadas {% endcomment %}
                    {% for jogador in vencedores %}   
                        <tr>
                            <td><p>{{ jogador.pk }}</p></td>
                            <td><p>{{ jogador.user.username }}</p></td>
                            <td><p>AO {{ jogador.valor }}</p></td>
                            <td><p>AO {{ aposta.premio }}</p></td>
                               </div>
                            </td>
                        </tr>
                {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-info">
                    <h3>Esta partida {% if not partida.concluido %} ainda {% endif %} não tem nenhum vencedor</h2>
                </div>
                {% endif %}
                

            {% if user.is_staff %}
                {% if partida.concluido %}
                    {% if not partida.encerrado %}
                        {% if vencedores|length > 0 %}
                            <a class="btn btn-primary" href="{% url 'blog:premiar-vencedores' partida.id %}" rel="tooltip" data-original-title="Premiar jogadores vencedores">
                            Atribuir Prêmio</a>
                        {% else %}
                        <a class="btn btn-danger" href="{% url 'blog:premiar-vencedores' partida.id %}">Devolver Dinheiro</a>
                        {% endif %}
                    {% else %}
                    <div class="alert alert-info">
                        <h5>Esta partida encontra-se encerrada...</h5>
                    </div>
                    {% endif %}

                {% else %}
                    <a class="btn" href="{% url 'blog:partida-update' partida.id %}" rel="tooltip" data-original-title="Atualizar da partida"><i class="icon-inbox"></i> Actualizar</a>
                {% endif %}
            {% endif %}
        
        
            </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

blog/templates/blog/partidas.html
{% extends 'blog/base.html' %}


{% block content %}
<div class="span9">
<div class="row-fluid">
    <div class="span12 box">
        <div class="box-header"><h3><i class="icon-play"></i> Lista de Partidas</h3></div>
        <div class="box-content">
            <div class="content-inner">
                <div class="marg20-btm">
                    Total de Partidas <span class="badge badge-inverse">{{partidas|length}}</span>
                    <form class="form-inline pull-right">
                        <input type="text" placeholder="Pesquisar partida">
                        <input class="btn" type="submit" value="Search">
                    </form>
                </div>

                {% if partidas %}
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Partida</th>
                            <th>Resultado</th>
                            <th>Data da partida</th>
                            <th>Estado</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% comment %} Mostrando a lista de todas partidas criadas {% endcomment %}
                    {% for partida in partidas %}   
                        <tr>
                            <td><p>{{ partida.pk }}</p></td>
                            <td><p>{{ partida.equipe1 }} vs {{ partida.equipe2 }}</p></td>
                            <td><p>{{ partida.placar1 }} - {{ partida.placar2 }}</p></td>
                            <td>{{ partida.data_partida }}</td>

                            {% comment %} Verificar se a partida já foi realizada {% endcomment %}
                            {% if  partida.concluido %}
                                <td><span class="label label-success">Concuída</span></td>
                            {% else %}
                                <td><span class="label label-important">Pendente</span></td>                        
                            {% endif %}

                            <td><div class="btn-group">
                                    {% if partida.concluido %}
                                        <a class="btn btn-info" href="{% url 'blog:vencedores' partida.id %}" rel="tooltip" data-original-title="Mostrar Jogadores vencedores"><i class="icon-signal"></i> Mostrar Vencedor</a>
                                    {% else %}
                                        <a class="btn" href="{% url 'blog:partida' partida.id %}" rel="tooltip" data-original-title="Selecionar partida"><i class="icon-ok"></i> Selecionar</a>
                                    {% endif %}
                                    <a class="btn" href="{% url 'blog:vencedores' partida.id %}" rel="tooltip" data-original-title="Mais informações sobre a partida">Detalhes</a>

                                  {% comment %} so actualiza se o usuario fizer parte a equipe de afministração do sistema {% endcomment %}
                                  {% if user.is_staff %}
                                    <a class="btn" href="{% url 'blog:partida-update' partida.id %}" rel="tooltip" data-original-title="Atualizar da partida"><i class="icon-inbox"></i> Actualizar</a>
                                  {% endif %}  
                                  
                               </div>
                            </td>
                        </tr>
                {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-info">
                    <h3>Sem partidas adicionadas</h2>
                </div>
                {% endif %}
                
    <!-- Paginação -->
    <div class="col-md-10 mb-4">
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info" href="?page=1">Primeiro</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">←</a>
        {% endif %}        
 
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num <  page_obj.number|add:'3' %}
                <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">→</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
        {% endif %}        
        
    {% endif %}
    </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

blog/templates/blog/perfil.html
{% extends 'blog/base.html' %}

{% block content %}

{% endblock content %}